spring:
  application:
    name: ms-pacientes
  datasource:
    url: jdbc:mysql://localhost:3306/ms_pacientes
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false  # Desactiva la opción open-in-view
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

  cloud:
    config:
      enabled: false  # Desactiva Spring Cloud Config

server:
  port: 8081

eureka:
  client:
    enabled: false  # Desactiva Eureka
